"""

Revision ID: 182e4ada711d
Revises: 5c024be37523
Create Date: 2023-01-06 13:31:12.289217

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '182e4ada711d'
down_revision = '5c024be37523'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
